In [ ]:
#NUMPY is a liner aljebra libray

#Numpy Array is the main way we use Numpy.

#Numpy Array are of the following two type:
    #1.Vector are strcitly 1-D array
    #2.Matrices are 2D array they still have 1 row and 1 column


In [8]:
# **Numpy array** 
import numpy as np

my_list = [1,2,3] # this is simply a list
my_list # displays the output of the list 

np.array(my_list) # casting the above list in to the array

arr = np.array(my_list) #assinging it to a varible 

arr #printing the array 


array([1, 2, 3])

In [12]:
# Numpy 2D array

# a list of list can be casted to a 2D array

my_list = [[1,2,3],[4,5,3],[7,8,9]] # making a 2D list
twodarray = np.array(my_list) #casting a a list of list in to array wil give you a 2D array.
twodarray

array([[1, 2, 3],
       [4, 5, 3],
       [7, 8, 9]])

In [17]:
# Numpy own array generation method for much faster and much simpler way of doing making Numpy array 

arr = np.arange(0,10) # similar to python owns range fuction. Has numpy.arange([start, ]stop, [step, ]dtype=None) 
                # will give you a list of numbers from 0 to 9 but not 10
print(arr)     
# Numpy range has skip fuction    
arr1 = np.arange(0,10,2) # jumps at a step of 2
print(arr1) 

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [32]:
# Numpy has special type of arrays

np.zeros(3) # we get a 1D vector out
print(np.zeros(3)) # we get a 1 D vector out

print(np.zeros((5,5))) # passing a tuple. first shows number of rows second number shows number of columns

print(np.ones((3,4))) # passing a tuple to make a 2D array of ONE's aka 1's array

# to print 1D vector of evenly spaced points we use linspace
print(np.linspace(0,5,10)) # as we can see here that we get a list of 10 evenly spaced numbers from 0 to 5 

#making an idendity matrix
np.eye(4)

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
# 1D array random samples of normaly distributed 

print(np.random.rand(5))

np.random.rand(5,5) # two dimention, unlike array we dont pass a tuple for row and column 

[0.79224744 0.7335511  0.46996556 0.57042258 0.50071372]


array([[0.38511575, 0.53710442, 0.68585984, 0.01443357, 0.52375121],
       [0.59583004, 0.38320839, 0.77971893, 0.40004844, 0.4778997 ],
       [0.7060499 , 0.75479571, 0.90787829, 0.08361414, 0.87938678],
       [0.36405719, 0.44779431, 0.68931585, 0.37120804, 0.94834684],
       [0.28247936, 0.20787853, 0.47118062, 0.96253133, 0.54239855]])

In [39]:
# returing a sample from normal or GAUSIAN distribution 
print(np.random.randn(2)) # getting two random numbers form normal distribution

print(np.random.randn(2,2)) #printing a two dimentions array of normal distribution 

[0.05730958 0.41115593]
[[ 0.37909271 -1.91578751]
 [-0.37728136  1.01038149]]


In [44]:
# getting a random number form low to a high number

print(np.random.randint(1,100))  #randint(low, high=None, size=None, dtype='l')  from `low` (inclusive) to `high` (exclusive).

print(np.random.randint(1,100,5)) #gives a array of 5 numbers

14
[16 32 55 71 72]


In [54]:
# important attribute of arrays
arr = np.arange(25)
print(arr)

print(arr.reshape(5,5)) #using the reshpe to change the format of the array arr. use the array to have the number that it contains
                        # rows * columns should be equal to the numbers in the array = 5 * 5 = 25

anarr = np.random.randint(0,50,10) 

print(anarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 9 30 16  3 33  3 49 31  7 33]


In [68]:
# useful function 
print(arr.max()) # returns maximum 
print(arr.min()) # retruns minimum

print(arr.argmax()) # returns index location of the max value 

print(arr.argmin()) # returns index location of the min value 

arr.shape # gives the shape of the array

arr = arr.reshape(5,5) #reshape
print(arr)
arr.shape

#curious about the data type 
arr.dtype

24
0
24
0
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


dtype('int32')

In [69]:
# for not typing a np.random.randint we do the following

from numpy.random import randint
randint(2,10)



2

In [80]:
#numpy indexing and selection : How to select the selects elements or group of elements 

# indexing starts at 0

arr = np.arange(0,11)
print(arr)

print(arr[8]) # we give the index position of the array arr

arr[1:7] #startig index and stopping index

print(arr[:9]) # everything from starting  till 9th index
print(arr[9:]) # everything beyond 9th index till end

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[0 1 2 3 4 5 6 7 8]
[ 9 10]


In [83]:
# numpy broadcasting feature

arr[0:5] = 100
print(arr) #it broad cast 100 from index 0 till 5

[100 100 100 100 100   5   6   7   8   9  10]


In [100]:
# slicing in the numpy array 
arr = np.arange(0,11)

slice_of_array = arr[0:6]  # it is just a refference of the array
slice_of_array

slice_of_array[:] = 99 

slice_of_array
arr # original array is modified.

#copying the array
arr_copy = arr.copy()
print(arr_copy)

arr_copy[:] = 100
print(arr_copy) # that the copy of the arr
print(arr) #now printing the original array it remians the same

[99 99 99 99 99 99  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


# indexing the 2D array

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

# there are 2 formats to grab the elements form the array as following 
    # Double bracket format
    # single bracket format with the ,

# Double bracket format
print('index for the first row and the first column  :', arr_2d[0][0]) # index for the first row and the first column

print('index the entire row back : ',arr_2d[0]) #index the entire row back of index 0

# single bracket , approach

arr_2d[2,1] # will give 8 - recommended to use it

# getting the submatrix
arr_2d[:2,1:] # 
print(arr_2d)
arr_2d[0:,:2]

In [149]:
#Conditional selection
arr = np.arange(1,11)
arr
bool_arr = arr > 5 # a array of Booliean values
arr[bool_arr] # now conditionally select the elemet 
arr[arr >5 ] # all the elements of array that are greater than 5
arr[arr <3] # all the elements of array that are less than 3


array([1, 2])

In [155]:
#practice
arr_2d = np.arange(50).reshape(5,10)
arr_2d
arr_2d[:3,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [165]:
#Numpy operation

#Array with Array 
#Array with Scalar operation 
#Universal Array Function 


arr = np.arange(0,11)

arr1 = arr + arr # array is getting added with array

print(arr1)

arr3 = arr - arr # array subsraction
print(arr3)

arr2 = arr * arr #arry is getting multiplied
print(arr2)
    
    
    

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [170]:
#array with scalar operation

r1 = arr + 100
print(r1)  # adding to array

r2 = arr - 100
print(r2)  # substracting to array 


[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]


In [175]:
# Numpy warning

arr / arr # gives us warning
# we still get an output with nan for 0/0 element in the 

1/ arr # we get the warning and but infinity this time 


arr**2 # array with the power of two

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [183]:
# Numpy Universal array function

print(np.sqrt(arr)) # gives the square root of the array

print(np.exp(arr))# exponent 

print(np.max(arr)) # returns the max

print(np.min(arr)) # returns the min

print(np.sin(arr)) # gets the sin value



[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
0
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
